prefixes:
  - name: Gold
  - name: Silver
  - name: Liquid
  - name: Lazy
  - name: Grass
  - name: Solid
  - name: Golden
    chainable: true
  - name: Silvered
    chainable: true
  - name: Gilded
    chainable: true
  - name: Diamond
  - name: Little
    chainable: true
  - name: Big
    chainable: true
  - name: Macho
  - name: Lord
  - name: Lady
  - name: Shining
  - name: Dull
  - name: Dirty
  - name: Queen
  - name: King
  - name: Brown
  - name: Black
  - name: Blonde
  - name: Pale
  - name: Tan
  - name: Dark
  - name: Bright
  - name: Hoof
  - name: Farrier
  - name: Wonderful
  - name: Vaulting
  - name: Harrying
  - name: Rude
    chainable: true
  - name: Polite
    chainable: true
  - name: Country
  - name: Farrier Harrier
    singular: true
  - name: Tall Hat
  - name: Small Hat
  - name: Hearty
    chainable: true
  - name: Lightning
  - name: Brutish
    chainable: true
  - name: Captain
    chainable: true
  - name: General
    chainable: true
  - name: Prototype
    chainable: true
  - name: Light
  - name: Star
  - name: Starry
    chainable: true
  - name: Moonshine
    chainable: true
  - name: Lazy Susan
    singular: true
  - name: Free
  - name: Bolting
  - name: Frosty
    chainable: true
  - name: Bony
    chainable: true
  - name: Mister
    chainable: true
  - name: Miss
    chainable: true
  - name: Missus
    chainable: true
  - name: Fancy
    chainable: true
  - name: Frenzied
    chainable: true
  - name: Quick
    chainable: true
  - name: Slow
    chainable: true
  - name: Red
  - name: Phantom
  - name: Jumbo
    chainable: true
  - name: Lil'
  - name: Whirlwind
  - name: Blazing
    chainable: true
  - name: Galloping
    chainable: true
  - name: Serenity
  - name: Hustling
    chainable: true
  - name: Radiant
  - name: Crimson
  - name: Sprinting
    chainable: true
  - name: Stormy
    chainable: true
  - name: Strong
  - name: Weak
  - name: Lucky
    chainable: true
  - name: Solar
  - name: Lunar
  - name: Cosmic
  - name: Heroic
    chainable: true
  - name: Flashy
  - name: Sapphire
  - name: Emerald
  - name: Topaz
  - name: Amethyst
  - name: Ruby
  - name: Citrine
  - name: Aquamarine
  - name: Opal
  - name: Garnet
  - name: Onyx
  - name: Agate
  - name: Apatite
  - name: Spinel
  - name: Jade
  - name: Pearl
  - name: Speedy
    chainable: true
  - name: Duke
    chainable: true
  - name: Duchess
    chainable: true
  - name: Silent
    chainable: true
  - name: Serenading
  - name: Majestic
    chainable: true
  - name: Harmonic
    chainable: true
  - name: Dazzling
    chainable: true
  - name: Dashing
    chainable: true
  - name: Striding
    chainable: true
  - name: Canter Banter
    singular: true
  - name: Giddy Up Giggles
    singular: true
  - name: Foal Play
    singular: true
  - name: Neigh Sayer
    singular: true
  - name: Jockey's
    chainable: true
  - name: Harmony's
    chainable: true
  - name: Hero's
    chainable: true
  - name: Phantom's
    chainable: true
  - name: Lord's
    chainable: true
  - name: Lady's
    chainable: true
  - name: Queen's
    chainable: true
  - name: King's
    chainable: true
  - name: Duke's
    chainable: true
  - name: Duchess's
    chainable: true
  - name: Captain's
    chainable: true
  - name: General's
    chainable: true
  - name: Hoofmaster 3000
    singular: true
  - name: Chardonneigh
    singular: true
  - name: Unstable
    chainable: true
  - name: Blackjack
    singular: true
  - name: Man About Town
    singular: true
  - name: Chancellor
  - name: First Place
    singular: true
  - name: Last Place
    singular: true
  - name: Go For Home
    singular: true
  - name: Neighbulous
    singular: true
  - name: Saddle Sores
    singular: true
  - name: Trot-tastic
    singular: true
  - name: Saddlebration
    singular: true
  - name: Canter Believe It
    singular: true
  - name: Hoofin' It
    singular: true
  - name: Trotally Radical
    singular: true
  - name: Tachyon
  - name: Admirable
    chainable: true
  - name: Memory
  - name: Bamboo
  - name: Helios
  - name: Hell's
    chainable: true
  - name: Bubble Gum
    chainable: true
  - name: Tactical
    chainable: true
  - name: Miraculous
    chainable: true
  - name: H.M.S.
    chainable: true
  - name: U.S.S.
    chainable: true
  - name: Sunday Morning
  - name: Sunday Best
    singular: true
  - name: Bourbon
  - name: Vodka
  - name: Mr.
    chainable: true
  - name: Ms.
    chainable: true
  - name: Mrs.
    chainable: true
  - name: Mx.
    chainable: true
  - name: Crowned
  - name: Uncrowned
  - name: Windy
    chainable: true
  - name: Special
    chainable: true
  - name: Symbolic
    chainable: true
  - name: Smart
    chainable: true
  - name: Seeking the
  - name: Hunting the
  - name: Watching the
  - name: Following the
  - name: Leading the
  - name: Beating the
  - name: Racing the
  - name: Losing to the
  - name: Reaching the
  - name: Jumping the
  - name: Eating the
  - name: Breaking the
  - name: Fixing the
  - name: Feeding the
  - name: Kicking the
  - name: Biting the
  - name: Clearing the
  - name: Tracking the
  - name: Crossing the
  - name: Topping the
  - name: Bottoming the
  - name: Doctor Whomst
    singular: true
  - name: Dr.
    chainable: true
  - name: Doctor
    chainable: true
  - name: Winning
    chainable: true
  - name: Losing
    chainable: true
  - name: 'No'
    chainable: true
  - name: 'False'
    chainable: true
  - name: 'True'
    chainable: true
  - name: One
    chainable: true

suffixes:
  - name: Ship
  - name: Galloper
  - name: Wonder
  - name: Vaulter
  - name: Harrier
  - name: Farrier
    chainable: true
  - name: Queen
  - name: King
  - name: Country
  - name: Hearted
    chainable: true
  - name: Hoof
  - name: Hoofed
    chainable: true
  - name: Soldier
  - name: General
  - name: Shadow
    chainable: true
  - name: Lord
  - name: Lady
  - name: Johnny
  - name: Bumpkin
  - name: Lightning
  - name: Brute
  - name: Captain
  - name: Pants
    chainable: true
  - name: Star
  - name: Sun
  - name: Moon
  - name: Maverick
  - name: Smoke
  - name: Devil
  - name: Smoky
    chainable: true
  - name: Bolter
  - name: Frosty
  - name: Bones
  - name: Mouse
  - name: Glacier
  - name: Railer
  - name: Snail
  - name: Viper
  - name: Red
    chainable: true
  - name: Hunter
  - name: Huntress
  - name: Killer
  - name: Lover
  - name: Blondie
  - name: River
  - name: Screamer
  - name: Scourge
  - name: Phantom
  - name: Tumbler
  - name: Baba Ghanoush
  - name: Hummus
  - name: Warrior
  - name: Streaker
  - name: Mischief
  - name: Victory
  - name: Streak
  - name: Serenity
  - name: Nova
  - name: Nebula
  - name: Hustle
  - name: Hustler
  - name: Comet
  - name: Chaser
  - name: Crimson
    chainable: true
  - name: Radiance
  - name: Echo
  - name: Dawn
    chainable: true
  - name: Dusk
    chainable: true
  - name: Twilight
    chainable: true
  - name: Honey
  - name: Walker
  - name: Sprinter
  - name: Storm
  - name: Flier
  - name: Fire
  - name: Water
  - name: Ice
  - name: Thunder
  - name: Paragon
  - name: Luck
  - name: Messenger
  - name: Express
    chainable: true
  - name: Arrow
  - name: Song
  - name: Sonata
  - name: Charger
  - name: Trotter
  - name: Hero
  - name: Ace
    chainable: true
  - name: Sapphire
    chainable: true
  - name: Emerald
    chainable: true
  - name: Topaz
    chainable: true
  - name: Amethyst
    chainable: true
  - name: Ruby
    chainable: true
  - name: Citrine
    chainable: true
  - name: Aquamarine
    chainable: true
  - name: Opal
    chainable: true
  - name: Garnet
    chainable: true
  - name: Onyx
    chainable: true
  - name: Agate
    chainable: true
  - name: Apatite
    chainable: true
  - name: Spinel
    chainable: true
  - name: Jade
    chainable: true
  - name: Pearl
    chainable: true
  - name: Appetite
  - name: Speedy
  - name: Duke
  - name: Duchess
  - name: Pacer
  - name: Serenade
  - name: Rhapsody
  - name: Dasher
  - name: Dancer
  - name: Dance
  - name: Tap Dance
  - name: Stride
  - name: Strider
  - name: Solstice
  - name: Affirmation
  - name: Saddle
    chainable: true
  - name: Folly
  - name: Chancellor
  - name: Merlot
  - name: Tachyon
  - name: Avenger
  - name: Groove
  - name: Messiah
  - name: Memory
  - name: Belief
  - name: San
  - name: Kun
  - name: Chan
  - name: Senpai
  - name: Sensei
  - name: Sama
  - name: Helios
  - name: Bubble Gum
  - name: Heart
    chainable: true
  - name: Tack
  - name: Tactics
  - name: Flash
  - name: Barb
  - name: Amazon
    chainable: true
  - name: Miracle
  - name: Halo
  - name: Jumper
  - name: Sunday
    chainable: true
  - name: Monday
    chainable: true
  - name: Tuesday
    chainable: true
  - name: Wednesday
    chainable: true
  - name: Thursday
    chainable: true
  - name: Friday
    chainable: true
  - name: Saturday
    chainable: true
  - name: Bourbon
    chainable: true
  - name: Vodka
    chainable: true
  - name: Street
  - name: Avenue
  - name: Boulevard
  - name: Lane
  - name: Drive
  - name: Road
  - name: Fiesta
  - name: Universe
  - name: Flower
    chainable: true
  - name: Festival
  - name: Fest
  - name: Laurel
  - name: Crown
  - name: Tiara
  - name: Headdress
  - name: Sky
  - name: Wind
  - name: Windy
    chainable: true
  - name: Day
  - name: Week
  - name: Month
  - name: Year
  - name: Symbol
  - name: Falcon
    chainable: true
  - name: Eagle
    chainable: true
  - name: Hawk
    chainable: true
  - name: Eye
  - name: Smarts
  - name: Pinnacle
  - name: Shark
    chainable: true
  - name: Whale
    chainable: true
  - name: Opera
  - name: Shuttle
  - name: Plane
  - name: Vessel
  - name: City
  - name: Town
  - name: Winner
  - name: Loser
  - name: Ticket
  - name: Turbo
    chainable: true
  - name: Twin
    chainable: true
  - name: Cross
  - name: One
